### ISSUE TITLE
gh-pages site is failing to build

### ISSUE THREAD

**Issue by Robinlovelace** [saferactive/site#3]
As shown here: https://github.com/saferactive/site/branches

Heads-up @layik I think it needs a .nojekyll file. I'm not sure if fixing this to auto-deploy with updated actions is a good use of time but will be great if we can get it working on gh pages as well as netlify, which is working and autodeploys with every commit, as shown here: https://lucid-mayer-06a7e9.netlify.app/

**Comment by layik** [comment]
I will do it for fun :) not a fan of Netlify like sites. You can still point the URL to Netlify if you wish to :)

**Comment by layik** [comment]
The reason is failing is that I did not do the reset properly.

**Comment by layik** [comment]
#5

**Comment by Robinlovelace** [comment]
> I will do it for fun :) not a fan of Netlify like sites. You can still point the URL to Netlify if you wish to :)

Sounds like a good mission! The site seems to have redirected OK, with continuous deployment within ~1m of each commit: https://www.saferactive.org/

Do we need to update the settings so https://saferactive.github.io/site/ works?

**Comment by Robinlovelace** [comment]
I think this is a good example of a hugodown-built website built with netlify: https://github.com/mdneuzerling/mdneuzerling.com

Trying to find gh-pages deploys but to no avail, we may be the first to do so via actions: https://www.google.com/search?channel=fs&q=hugodown+%22github+actions%22

Context: https://github.com/r-lib/hugodown/issues/31

**Comment by Robinlovelace** [comment]
Thinking about it, I think cracking-on with issues in the trafficalmr package is a better use of time. Plan to remove the gh-pages branch and the actions.yml on Monday. I think it's good to play and experiment but this repo may not be the best place for that...

**Comment by layik** [comment]
Right your call. I am against this theme which relies fully on Netlify, that is not reproducibility as we know it. I cannot even run it on my machine, almost impossible with big letters and red colour docs nothing changes.

**Comment by Robinlovelace** [comment]
>  I cannot even run it on my machine

Happy to do a co-coding session to reproduce the website locally.

**Comment by layik** [comment]
It is done now but this is the worst academic thing I have ever seen. I will document this for myself as last time I did this was not this hard, but wont try and contribute upstream as I believe they want to keep this to themselves + netlify.

Plan should remain the same and effort should be directed elsewhere.

<img width="920" alt="Screenshot 2020-10-04 at 21 15 21" src="https://user-images.githubusercontent.com/408568/95026110-dbec1a80-0686-11eb-9e22-2786f49b5c31.png">

**Comment by Robinlovelace** [comment]
Thanks for feedback. Can always change + improve things. What do you think we could do to improve the site?
